name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'GitHub ref to checkout'
        required: true
        default: main
      tag:
        description: 'Docker tag to push (do NOT use "latest" or version numbers)'
        required: true
        default: 'HEAD'
  push:
    tags:
      - v*

jobs:
  docker-image:
    # Documentation: https://github.com/zakodium/workflows#docker-image
    uses: zakodium/workflows/.github/workflows/docker-image.yml@21-create-a-reusable-workflow-for-docker-image-creation
    with:
      ref: ${{ github.event.inputs.ref }}
      tag: ${{ github.event.inputs.tag }}
